# Created by trellis-cli v1.8.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  brucesmallwood.com:
    site_hosts:
    - canonical: brucesmallwood.test
      redirects:
      - www.brucesmallwood.test
    local_path: ../site
    admin_email: admin@brucesmallwood.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
