# Created by trellis-cli v1.8.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  brucesmallwood.com:
    site_hosts:
    - canonical: brucesmallwood.com
      redirects:
      - www.brucesmallwood.com
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
